[package]
name = "yamlrustler"
version = "0.1.4"
authors = ["Jørgen Orehøj Erichsen <joe@erichsen.net>"]
edition = "2021"

[lib]
name = "yamlrustler"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
yaml-rust2 = "0.8"